# Generated by Django 3.2.4 on 2021-07-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nrvolcoeff',
            name='c0',
        ),
        migrations.RemoveField(
            model_name='nrvolcoeff',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='nrvolcoeff',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='nrxcgcoeff',
            name='c0',
        ),
        migrations.RemoveField(
            model_name='nrxcgcoeff',
            name='c1',
        ),
        migrations.RemoveField(
            model_name='nrxcgcoeff',
            name='c2',
        ),
        migrations.RemoveField(
            model_name='nrxcgcoeff',
            name='c3',
        ),
        migrations.AddField(
            model_name='nrvolcoeff',
            name='vol_c0',
            field=models.FloatField(default=0, help_text='coeficiente ordem 0: nr^0', verbose_name='c0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrvolcoeff',
            name='vol_c1',
            field=models.FloatField(default=0, help_text='coeficiente ordem 1: nr^1', verbose_name='c1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrvolcoeff',
            name='vol_c2',
            field=models.FloatField(default=0, help_text='coeficiente ordem 2: nr^2', verbose_name='c2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrxcgcoeff',
            name='xcg_c0',
            field=models.FloatField(default=0, help_text='coeficiente ordem 0: nr^0', verbose_name='c0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrxcgcoeff',
            name='xcg_c1',
            field=models.FloatField(default=0, help_text='coeficiente ordem 1: nr^1', verbose_name='c1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrxcgcoeff',
            name='xcg_c2',
            field=models.FloatField(default=0, help_text='coeficiente ordem 2: nr^2', verbose_name='c2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nrxcgcoeff',
            name='xcg_c3',
            field=models.FloatField(default=0, help_text='coeficiente ordem 3: nr^3', verbose_name='c0'),
            preserve_default=False,
        ),
    ]
