# Generated by Django 3.2.4 on 2021-06-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bloco_usina'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocodata',
            options={'ordering': ['data'], 'verbose_name': 'dados de bloco', 'verbose_name_plural': 'dados de blocos'},
        ),
        migrations.RenameField(
            model_name='blocodata',
            old_name='datetime',
            new_name='data',
        ),
    ]
