# Generated by Django 3.2.4 on 2021-07-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210705_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='usina',
            name='qtd_sensores',
            field=models.IntegerField(default=1),
        ),
    ]
