# Generated by Django 3.2.4 on 2021-07-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usina_qtd_sensores'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloco',
            name='pz_i_0',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloco',
            name='pz_i_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloco',
            name='pz_i_rel',
            field=models.CharField(choices=[('min', 'Mínimo entre piezômetros'), ('max', 'Mínimo entre piezômetros'), ('avg', 'Mínimo entre piezômetros')], default=1, max_length=3, verbose_name='Escolha relação i'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloco',
            name='pz_j_0',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloco',
            name='pz_j_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloco',
            name='pz_j_rel',
            field=models.CharField(choices=[('min', 'Mínimo entre piezômetros'), ('max', 'Mínimo entre piezômetros'), ('avg', 'Mínimo entre piezômetros')], default=1, max_length=3, verbose_name='Escolha relação j'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloco',
            name='pz_m_0',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloco',
            name='pz_m_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloco',
            name='pz_m_rel',
            field=models.CharField(choices=[('min', 'Mínimo entre piezômetros'), ('max', 'Mínimo entre piezômetros'), ('avg', 'Mínimo entre piezômetros')], default=1, max_length=3, verbose_name='Escolha relação m'),
            preserve_default=False,
        ),
    ]
