# Generated by Django 3.2.4 on 2021-07-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usina_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usina',
            name='min_fsd',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='usina',
            name='min_fst',
            field=models.FloatField(default=1.0),
        ),
    ]
