# Generated by Django 3.2.4 on 2021-07-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210729_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='pz_i_rel',
            field=models.CharField(choices=[('min', 'Mínimo entre piezômetros'), ('max', 'Máximo entre piezômetros'), ('avg', 'Média entre piezômetros')], max_length=3, verbose_name='Escolha relação i'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='pz_j_rel',
            field=models.CharField(choices=[('min', 'Mínimo entre piezômetros'), ('max', 'Máximo entre piezômetros'), ('avg', 'Média entre piezômetros')], max_length=3, verbose_name='Escolha relação j'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='pz_m_rel',
            field=models.CharField(choices=[('min', 'Mínimo entre piezômetros'), ('max', 'Máximo entre piezômetros'), ('avg', 'Média entre piezômetros')], max_length=3, verbose_name='Escolha relação m'),
        ),
    ]
