# Generated by Django 3.2.4 on 2021-08-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210823_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='angulo_sedimento',
            field=models.FloatField(verbose_name='Ângulo Sedimento [rad]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='area',
            field=models.FloatField(verbose_name='Area [m2]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='c',
            field=models.FloatField(verbose_name='c'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='comprimento',
            field=models.FloatField(verbose_name='Comprimento [m]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='cota_base_jusante',
            field=models.FloatField(verbose_name='Cota da base jusante [m]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='cota_base_montante',
            field=models.FloatField(verbose_name='Cota da base de montante [m]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='cota_ogiva',
            field=models.FloatField(verbose_name='Cota da ogiva [m]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='cota_sedimento',
            field=models.FloatField(verbose_name='Cota do sedimento [m]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='cota_terreno',
            field=models.FloatField(verbose_name='Cota do sedimento [m]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='dist_xi',
            field=models.FloatField(verbose_name='Distacia Xi [m]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='dist_xj',
            field=models.FloatField(verbose_name='Distacia Xj [m]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='dist_xm',
            field=models.FloatField(verbose_name='Distacia Xm [m]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='gamma_agua',
            field=models.FloatField(verbose_name='Gamma da água [KN/m2]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='gamma_c',
            field=models.FloatField(verbose_name='Gamma-C'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='gamma_concreto',
            field=models.FloatField(verbose_name='Gamma do concreto [KN/m2]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='gamma_enchimento',
            field=models.FloatField(verbose_name='Gamma do enchimento [KN/m2]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='gamma_phi',
            field=models.FloatField(verbose_name='Gamma-Phi'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='gamma_sedimento',
            field=models.FloatField(verbose_name='Gamma do sedimento [KN/m2]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='largura',
            field=models.FloatField(verbose_name='Volume [m3]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='phi',
            field=models.FloatField(verbose_name='Phi'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='pz_i_rel',
            field=models.CharField(choices=[('min', 'Mínimo entre piezômetros'), ('max', 'Máximo entre piezômetros'), ('avg', 'Média entre piezômetros')], max_length=3, verbose_name='Escolha relação - Piezômetros i'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='pz_j_rel',
            field=models.CharField(choices=[('min', 'Mínimo entre piezômetros'), ('max', 'Máximo entre piezômetros'), ('avg', 'Média entre piezômetros')], max_length=3, verbose_name='Escolha relação - Piezômetros j'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='pz_m_rel',
            field=models.CharField(choices=[('min', 'Mínimo entre piezômetros'), ('max', 'Máximo entre piezômetros'), ('avg', 'Média entre piezômetros')], max_length=3, verbose_name='Escolha relação - Piezômetros m'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='v_enchimento',
            field=models.FloatField(verbose_name='Volume do enchimento [m3]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='volume_bloco',
            field=models.FloatField(verbose_name='Volume [m3]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='xcg_bloco',
            field=models.FloatField(verbose_name='Xcg [m]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='xcg_enchimento',
            field=models.FloatField(verbose_name='Xcg do enchimento [m]'),
        ),
        migrations.AlterField(
            model_name='nrvolcoeff',
            name='vol_c0',
            field=models.FloatField(help_text='coeficiente ordem 0: nr^0', verbose_name='volume - c0'),
        ),
        migrations.AlterField(
            model_name='nrvolcoeff',
            name='vol_c1',
            field=models.FloatField(help_text='coeficiente ordem 1: nr^1', verbose_name='volume - c1'),
        ),
        migrations.AlterField(
            model_name='nrvolcoeff',
            name='vol_c2',
            field=models.FloatField(help_text='coeficiente ordem 2: nr^2', verbose_name='volume - c2'),
        ),
        migrations.AlterField(
            model_name='nrxcgcoeff',
            name='xcg_c0',
            field=models.FloatField(help_text='coeficiente ordem 0: nr^0', verbose_name='peso da água - c0'),
        ),
        migrations.AlterField(
            model_name='nrxcgcoeff',
            name='xcg_c1',
            field=models.FloatField(help_text='coeficiente ordem 1: nr^1', verbose_name='peso da água - c1'),
        ),
        migrations.AlterField(
            model_name='nrxcgcoeff',
            name='xcg_c2',
            field=models.FloatField(help_text='coeficiente ordem 2: nr^2', verbose_name='peso da água - c2'),
        ),
        migrations.AlterField(
            model_name='nrxcgcoeff',
            name='xcg_c3',
            field=models.FloatField(help_text='coeficiente ordem 3: nr^3', verbose_name='peso da água - c3'),
        ),
    ]
