# Generated by Django 3.2.4 on 2021-08-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210824_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloco',
            name='bloco_especial',
            field=models.BooleanField(default=False, verbose_name='Usina com dois valores de empuxo?'),
        ),
    ]
