# Generated by Django 3.2.4 on 2021-08-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bloco_bloco_especial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloco',
            name='bloco_especial',
        ),
        migrations.AddField(
            model_name='bloco',
            name='tipo',
            field=models.IntegerField(choices=[(None, 'Escolha o tipo do bloco'), (1, 'Tipo Blocos 2-4'), (2, 'Tipo Blocos 6-15'), (3, 'Tipo Bloco 5')], default=1, verbose_name='Tipo do Bloco'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='c',
            field=models.FloatField(verbose_name='c [kN]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='gamma_agua',
            field=models.FloatField(verbose_name='Gamma da água [kN/m3]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='gamma_concreto',
            field=models.FloatField(verbose_name='Gamma do concreto [kN/m3]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='gamma_enchimento',
            field=models.FloatField(verbose_name='Gamma do enchimento [kN/m3]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='gamma_sedimento',
            field=models.FloatField(verbose_name='Gamma do sedimento [kN/m3]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='largura',
            field=models.FloatField(verbose_name='Largura [m3]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='phi',
            field=models.FloatField(verbose_name='Phi [rad]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='volume_bloco',
            field=models.FloatField(verbose_name='Volume Bloco [m3]'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='xcg_bloco',
            field=models.FloatField(verbose_name='Xcg Bloco [m]'),
        ),
    ]
