# Generated by Django 3.2.4 on 2021-08-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210824_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloco',
            name='cota_terreno',
            field=models.FloatField(verbose_name='Cota do terreno [m]'),
        ),
    ]
