# Generated by Django 3.2.4 on 2021-07-20 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20210705_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='BundleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_data', models.DateTimeField(db_index=True)),
                ('already_converted_to_block_data', models.BooleanField(default=False)),
                ('usina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_data', to='app.usina')),
            ],
            options={
                'unique_together': {('usina', 'bundle_data')},
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(db_index=True)),
                ('type', models.CharField(choices=[(None, 'Selecione o tipo do sensor...'), ('nr', 'Nível do Reservatório'), ('pz', 'Medição do Piezômetro')], default=None, max_length=2)),
                ('value', models.FloatField()),
                ('bundle_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='sensor_data.bundledata')),
            ],
        ),
    ]
