# Generated by Django 3.2.4 on 2021-07-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='sensordata',
            unique_together={('bundle_data', 'type', 'number')},
        ),
    ]
