# Generated by Django 3.2.4 on 2021-08-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_auto_20210720_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundledata',
            options={'verbose_name_plural': 'Pacotes de Dados'},
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'ordering': ('type', 'number')},
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='number',
            field=models.IntegerField(default=None),
        ),
    ]
